### ISSUE TITLE
WebDAVFileManager 这个不是 public 的使用不了

### ISSUE THREAD

**Issue by chinamingsss** [fanjiashu/WebDAVKitSwift#1]
大佬，你看一下 WebDAVFileManager 这个好像外部使用不了吧，并且想问一下 你这个能支持 cocoapods 吗

**Comment by fanjiashu** [comment]
感谢您的建议，WebDAVFileManager 是我建的示例，不是库本身，你可以直接参考copy一份，因为每个业务场景不一样，按需取即可。
cocoapods仓库我没上传，后面有时间了我建一个cocoapods库
